PhoneDirectory.WEB/Controllers/AdminController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PhoneDirectory.BLL.DTO;
using PhoneDirectory.BLL.Infrastructure;
using PhoneDirectory.BLL.Interfaces;
using PhoneDirectory.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace PhoneDirectory.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private IAdminService adminService;

        public AdminController(IAdminService service)
        {
            // Сервис, внедренный через зависимость
            adminService = service;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AllNumbers()
        {
            IEnumerable<UserDTO> dtosUsers = adminService.GetUsers();
            var mapperUsers = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
            var users = mapperUsers.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers);
            return View(users);
        }


        public IActionResult Users(int? id)
        {
            if (id == null)
            {
                IEnumerable<UserDTO> dtosUsers = adminService.GetUsers();
                if (dtosUsers == null) return NotFound();
                var mapperUsers = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
                var model = mapperUsers.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers);
                return View("Users", model);
            }
            else
            {
                StructuralDivisionDTO dtostructuralDivision = adminService.GetStructuralDivision((int)id);
                if (dtostructuralDivision == null) return NotFound();
                IEnumerable<UserDTO> dtosUsers = adminService.GetUsers(dtostructuralDivision.Id);
                if (dtosUsers == null) return NotFound();
                var mapperGroup = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
                var mapperUser = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
                StructuralDivisionUsersViewModel model = new StructuralDivisionUsersViewModel
                {
                    StructuralDivision = mapperGroup.Map<StructuralDivisionDTO, StructuralDivisionViewModel>(dtostructuralDivision),
                    Users = mapperUser.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers)
                };
                return View("StructuralDivisionUsers", model);
            }
        }

        public IActionResult DepStaff(int? id)
        {
            if (id == null)
            {
                IEnumerable<UserDTO> dtosUsers = adminService.GetUsers();
                if (dtosUsers == null) return NotFound();
                var mapperStaff = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
                var model = mapperStaff.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers);
                return View("DepStaff", model);
            }
            else
            {
                StructuralDivisionDTO dtostructuralDivision = adminService.GetStructuralDivision((int)id);
                if (dtostructuralDivision == null) return NotFound();
                IEnumerable<UserDTO> dtosUsers = adminService.GetUsers(dtostructuralDivision.Id);
                if (dtosUsers == null) return NotFound();
                var mapperStructuralDivision = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
                var mapperUser = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
                StructuralDivisionUsersViewModel model = new StructuralDivisionUsersViewModel
                {
                    StructuralDivision = mapperStructuralDivision.Map<StructuralDivisionDTO, StructuralDivisionViewModel>(dtostructuralDivision),
                    Users = mapperUser.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers)
                };
                return View("StructuralDivisionUsers", model);
            }
        }

        
        public IActionResult StructuralDivisions()
        {
            StructuralDivisionsFilterViewModel filter = new StructuralDivisionsFilterViewModel { StrucDivId = 1, PostId = 1, UseStructuralDivision = false, UsePost= false };            
            var dtosStructuralDivisions = adminService.GetStructuralDivisions();
            var mapperStructuralDivision = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
            ViewData["StructuralDivisions"] = mapperStructuralDivision.Map<IEnumerable<StructuralDivisionDTO>, List<StructuralDivisionViewModel>>(dtosStructuralDivisions);
            ViewData["StrucDivId"] = new SelectList(adminService.GetStructuralDivisions1(), "Id", "NameStrucDiv", filter.StrucDivId);            
            ViewData["PostId"] = new SelectList(adminService.GetPosts(), "Id", "NamePost", filter.PostId);           
            return View(filter);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StructuralDivisions(StructuralDivisionsFilterViewModel filter)
        {           
            var mapperFilter = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionsFilterViewModel, StructuralDivisionsFilterDTO>()).CreateMapper();
            var dtosStructuralDivisions = adminService.GetStructuralDivisions(mapperFilter.Map<StructuralDivisionsFilterViewModel, StructuralDivisionsFilterDTO>(filter));            
            var mapperGroup = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
            ViewData["StructuralDivisions"] = mapperGroup.Map<IEnumerable<StructuralDivisionDTO>, List<StructuralDivisionViewModel>>(dtosStructuralDivisions);
            ViewData["StrucDivId"] = new SelectList(adminService.GetStructuralDivisions(), "Id", "NameStrucDiv", filter.StrucDivId);            
            ViewData["PostId"] = new SelectList(adminService.GetPosts(), "Id", "NamePost", filter.PostId);          
            return View(filter);
        }

        [HttpGet]
        public ActionResult StructuralDivisionEdit(int? id)
        {
            if (id == null) return NotFound();
            var dtoDivisionPost = adminService.GetDivisionPost((int)id);
            var mapperDivisionPost = new MapperConfiguration(cfg => cfg.CreateMap<DivisionPostDTO, StructuralDivisionCreateViewModel>()).CreateMapper();            
            StructuralDivisionCreateViewModel model = new StructuralDivisionCreateViewModel { StrucDivId = 1 };
            ViewData["StrucDivId"] = new SelectList(adminService.GetStructuralDivisions1(), "Id", "NameStrucDiv", model.StrucDivId);            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StructuralDivisionEdit(StructuralDivisionCreateViewModel model)
        {            
            if (ModelState.IsValid)
            {
                try
                {
                    var mapperDivisionPost = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionCreateViewModel, DivisionPostDTO>()).CreateMapper();
                    var dtoDivisionPost = mapperDivisionPost.Map<StructuralDivisionCreateViewModel, DivisionPostDTO>(model);
                    ViewData["StrucDivId"] = new SelectList(adminService.GetStructuralDivisions1(), "Id", "NameStrucDiv", model.StrucDivId);                    
                    adminService.UpdateDivisionPost(dtoDivisionPost);
                    return RedirectToAction("StructuralDivisions");
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }            
            return View(model);
        }

        [HttpGet]
        public IActionResult StructuralDivisionDelete(int? id)
        {
            if (id == null) return NotFound();
            DivisionPostDTO dtodivisionPost = adminService.GetDivisionPost((int)id);
            if (dtodivisionPost == null) return NotFound();
            var mapperGroup = new MapperConfiguration(cfg => cfg.CreateMap<DivisionPostDTO, StructuralDivisionViewModel>()).CreateMapper();
            var model = mapperGroup.Map<DivisionPostDTO, StructuralDivisionViewModel>(dtodivisionPost);
            return View(model);
        }

        [HttpPost, ActionName("StructuralDivisionDelete")]
        [ValidateAntiForgeryToken]
        public IActionResult StructuralDivisionDeleteConfirmed(int id)
        {
            try
            {
                adminService.DeleteDivisionPost(id);
                return RedirectToAction("StructuralDivisions");
            }
            catch (ValidationException ex)
            {
                ModelState.AddModelError(ex.Property, ex.Message);
            }
            DivisionPostDTO dtoDivisionPost = adminService.GetDivisionPost(id);
            if (dtoDivisionPost == null) return NotFound();
            var mapperGroup = new MapperConfiguration(cfg => cfg.CreateMap<DivisionPostDTO, StructuralDivisionViewModel>()).CreateMapper();
            var model = mapperGroup.Map<DivisionPostDTO, StructuralDivisionViewModel>(dtoDivisionPost);
            return View(model);
        }

        [HttpGet]
        public IActionResult UserCreate(int? id)
        {
            if (id == null || id < 1 || id > 2) return NotFound();
            var dtoRole = adminService.GetRole((int)id);
            ViewData["Role"] = dtoRole.Name;

PhoneDirectory.WEB/Controllers/EmployeeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PhoneDirectory.BLL.DTO;
using PhoneDirectory.BLL.Interfaces;
using PhoneDirectory.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhoneDirectory.WEB.Controllers
{
    [Authorize(Roles = "employee")]
    public class EmployeeController : Controller
    {
        private IEmployeeService employeeService;

        public EmployeeController(IEmployeeService service)
        {
            // Сервис, внедренный через зависимость
            employeeService = service;
        }
        public IActionResult Index()
        {
            IEnumerable<UserDTO> dtosUsers = employeeService.GetUsers();
            var mapperUsers = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
            var users = mapperUsers.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers);
            return View(users);
        }       

        public IActionResult StructuralDivisions()
        {
            StructuralDivisionsFilterViewModel filter = new StructuralDivisionsFilterViewModel { StrucDivId = 1, PostId = 1, UseStructuralDivision = false, UsePost = false };
            var dtosStructuralDivisions = employeeService.GetStructuralDivisions();
            var mapperStructuralDivision = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
            ViewData["StructuralDivisions"] = mapperStructuralDivision.Map<IEnumerable<StructuralDivisionDTO>, List<StructuralDivisionViewModel>>(dtosStructuralDivisions);
            ViewData["StrucDivId"] = new SelectList(employeeService.GetStructuralDivisions1(), "Id", "NameStrucDiv", filter.StrucDivId);
            ViewData["PostId"] = new SelectList(employeeService.GetPosts(), "Id", "NamePost", filter.PostId);
            return View(filter);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StructuralDivisions(StructuralDivisionsFilterViewModel filter)
        {
            var mapperFilter = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionsFilterViewModel, StructuralDivisionsFilterDTO>()).CreateMapper();
            var dtosStructuralDivisions = employeeService.GetStructuralDivisions(mapperFilter.Map<StructuralDivisionsFilterViewModel, StructuralDivisionsFilterDTO>(filter));
            var mapperGroup = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
            ViewData["StructuralDivisions"] = mapperGroup.Map<IEnumerable<StructuralDivisionDTO>, List<StructuralDivisionViewModel>>(dtosStructuralDivisions);
            ViewData["StrucDivId"] = new SelectList(employeeService.GetStructuralDivisions(), "Id", "NameStrucDiv", filter.StrucDivId);
            ViewData["PostId"] = new SelectList(employeeService.GetPosts(), "Id", "NamePost", filter.PostId);
            return View(filter);
        }       

        public IActionResult DepStaff(int? id)
        {
            if (id == null)
            {
                IEnumerable<UserDTO> dtosUsers = employeeService.GetUsers();
                if (dtosUsers == null) return NotFound();
                var mapperStaff = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
                var model = mapperStaff.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers);
                return View("DepStaff", model);
            }
            else
            {
                StructuralDivisionDTO dtostructuralDivision = employeeService.GetStructuralDivision((int)id);
                if (dtostructuralDivision == null) return NotFound();
                IEnumerable<UserDTO> dtosUsers = employeeService.GetUsers(dtostructuralDivision.Id);
                if (dtosUsers == null) return NotFound();
                var mapperStructuralDivision = new MapperConfiguration(cfg => cfg.CreateMap<StructuralDivisionDTO, StructuralDivisionViewModel>()).CreateMapper();
                var mapperUser = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
                StructuralDivisionUsersViewModel model = new StructuralDivisionUsersViewModel
                {
                    StructuralDivision = mapperStructuralDivision.Map<StructuralDivisionDTO, StructuralDivisionViewModel>(dtostructuralDivision),
                    Users = mapperUser.Map<IEnumerable<UserDTO>, List<UserViewModel>>(dtosUsers)
                };
                return View("StructuralDivisionUsers", model);
            }
        }
    }
}

PhoneDirectory.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Справочник</title>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <div class="bg-light">
            <div class="container">
                <div class="d-flex flex-column flex-sm-row">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <span class="text-dark font-weight-light mx-auto ml-sm-0">@User.FindFirst(x => x.Type == "FullName").Value</span>
                        <span class="mx-auto mr-sm-0"><a class="font-weight-bold" asp-controller="Home" asp-action="Logout">Выйти</a></span>
                    }
                    else
                    {
                        <span class="mx-auto mr-sm-0"><a class="font-weight-bold" asp-controller="Home" asp-action="Login">Войти</a></span>
                    }
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Справочник</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Администратор</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="Index">Админка</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="AllNumbers">Все номера</a>
                                        <a class="dropdown-item" asp-controller="Admin" asp-action="StructuralDivisions">Отделы</a>
                                    </div>
                                </li>
                            }
                            @if (User.IsInRole("employee"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Сотрудник</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                        <a class="nav-link" asp-controller="Employee" asp-action="Index">Все номера</a>
                                        <a class="dropdown-item" asp-controller="Employee" asp-action="StructuralDivisions">Отделы</a>
                                    </div>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            &copy; 2021 - Справочник
        </div>
    </footer>    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>